### ISSUE TITLE
Bot não está respondendo

### ISSUE THREAD

**Issue by luis-kaufmann-silva** [rennancockles/jaiminho_bot#1]
O bot não responde a nenhum comando. Tentei /start, /status e /rastreio e não obtive nenhuma resposta.

**Comment by rennancockles** [comment]
Ele está parado. Eu tinha começado o desenvolvimento dele por não ter achado nenhum que fizesse o mesmo. Porém descobri um já bem completo @RastreioBot

**Comment by luis-kaufmann-silva** [comment]
Ah. Ok, obrigado.
